org: bjtowne
app: make-chase
service: make-chase-service

frameworkVersion: '2'

custom:
  apiGatewayTags:
    thedeepdarkweb: 'serverless-auto'
  serverless-offline:
    noPrependStageInUrl: true
    printOutput: true
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

package:
  include:
    - src/**

plugins:
  - serverless-plugin-tracing
  - serverless-tag-api-gateway
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  tracing: true
  websocketsApiRouteSelectionExpression: $request.body.action
  tags:
    thedeepdarkweb: 'serverless-auto'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
  environment:
    AWS_STAGE:
      ${self:provider.stage}

functions:
  graphql:
    handler: src/handlers/graphql.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

  websocketConnect:
    handler: src/handlers/websocket.connect
    events:
      - websocket:
          route: $connect

  websocketDisconnect:
    handler: src/handlers/websocket.disconnect
    events:
      - websocket:
          route: $disconnect

  websocketDefault:
    handler: src/handlers/websocket.defaulter
    events:
      - websocket:
          route: $default

  websocketSubscribe:
    handler: src/handlers/websocket.subscribe
    events:
      - websocket:
          route: subscribe
